env:
  browser: true
  es2021: true
  jest: true
extends:
  - standard
  - eslint:recommended
  - plugin:react/recommended
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  quotes: [
    error,
    single
  ],
  jsx-quotes: [
    error,
    prefer-single
  ],
  semi: [
    error,
    always
  ],
  no-use-before-define: 0,
  '@typescript-eslint/no-use-before-define': 2,
}
settings:
  # supress warning
  react: {
    version: 'detect'
  }
